#cloud-config
repo_update: true
repo_upgrade: all
package_upgrade: true

packages:
  - docker 

runcmd:
  - sudo service docker start
  - sudo usermod -a -G docker ec2-user
  - docker pull jaylees/comsm0010-worker
  - docker run jaylees/comsm0010-worker
  - echo "Setup complete" >> /home/ec2-user/output.status