#cloud-config
repo_update: true
repo_upgrade: all
package_upgrade: true

packages:
  - awslogs 

runcmd:
  - sudo service awslogs start
  - echo ECS_CLUSTER=COMSM0010-worker-cluster >> /etc/ecs/ecs.config
