#cloud-config
repo_update: true
repo_upgrade: all
package_upgrade: true

packages:
  - awslogs 

runcmd:
  - sudo service awslogs start
  - echo ECS_CLUSTER=COMSM0010-monitor-cluster >> /etc/ecs/ecs.config

write_files:
-   content: |
      global:
        scrape_interval:     15s
        evaluation_interval: 15s

      # A scrape configuration containing exactly one endpoint to scrape.
      scrape_configs:
        - job_name: ecs 
          ec2_sd_configs:
            - region: us-east-1
              port: 8080
    path: /etc/prometheus/prometheus.yml
