#cloud-config
runcmd:
  - echo ECS_CLUSTER=COMSM0010-monitor-cluster >> /etc/ecs/ecs.config

write_files:
-   content: |
      global:
        scrape_interval:     15s
        evaluation_interval: 15s

      # A scrape configuration containing exactly one endpoint to scrape.
      scrape_configs:
        - job_name: ecs 
          ec2_sd_configs:
            - region: us-east-1
              port: 8080
            - region: us-east-1
              port: 2112 
    path: /etc/prometheus/prometheus.yml
-   content: |
      version: '3'

      services:
        grafana:
          image: 615057327315.dkr.ecr.us-east-1.amazonaws.com/jaylees/comsm0010-grafana:latest 
          deploy:
            replicas: 1 
            restart_policy:
              condition: on-failure
          ports:
            - "3000:3000" 

        prom:
          image: prom/prometheus:latest
          deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
          ports:
            - "9090:9090"
          volumes:
            - /etc/prometheus:/etc/prometheus
      
    path: /home/ec2-user/docker-compose.yml

runcmd:
  - sudo $(aws ecr get-login --no-include-email --region us-east-1)
  - sudo service docker start
  - sudo docker pull 615057327315.dkr.ecr.us-east-1.amazonaws.com/jaylees/comsm0010-grafana:latest
  - sudo docker pull prom/prometheus:latest
  - cd /home/ec2-user
  - docker-compose up -d
