sudo: required

language: go 

services:
  - docker

before_install:
  # https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - chmod +x deploy.sh

after_success:
  ./deploy.sh
