apiVersion: 1

datasources:
- name: Prometheus-Docker
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prom:9090
  basicAuth: false
  isDefault: true
  editable: true
- name: Prometheus-ECR
  type: prometheus
  access: proxy
  orgId: 1
  url: http://localhost:9090
  basicAuth: false
  editable: true
